name: Secrets and Env's Pipeline

on:
  workflow_dispatch:

env:
  MY_SECRET: ${{ secrets.MY_SECRET }}
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Debug Info
        run: echo "GitHub Actions is running!"
